version: '3.7'

services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    ports:
      - 15433:5432

  redis:
    image: redis
    ports:
      - 16380:6379

  server:
    build:
      context: ./server
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
    ports:
      - '7002:7002'

  nginx:
    image: nginx:alpine
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=computer-service.dev.local
    networks:
      - default
      - outside

networks:
  outside:
    external: true
    name: nginx-proxy
