version: '3.7'

services:

  redis:
    image: redis
    ports:
      - 16380:6379

  client:
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - '7002:7002'
    networks:
      - default
      - serverdb

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=computer-service.dev.local
    networks:
      - default
      - outside

networks:
  serverdb:
    name: serverdb
    external: true
  outside:
    external: true
    name: nginx-proxy
